### ISSUE TITLE
Get-NetBackupJob

### ISSUE THREAD

**Issue by KavyaKanya** [lazywinadmin/NetBackupPS#6] opened 2020-09-12 08:57 UTC
I've imported the NetBackup Module into PS but when I try to run a set of commands I get the below error

![image](https://user-images.githubusercontent.com/69708851/92991831-e55ce980-f503-11ea-9e86-c1e8a16d183f.png)

**Comment by AspenForester** [comment] 2020-09-14 19:58
If you do `get-help Get-NetBackupJob` you'll see that there are multiple parametersets, and at least one parameter must be provided in order for the command to  know how you would like it to operate.

**Comment by KavyaKanya** [comment] 2020-09-15 01:11
Hello AspenForeser

Any thoughts on how to integrate the NetBackup tool and Zabbix (i.e feedin the data from Backup tool to Zabbix) via PowerShell script

**Comment by AspenForester** [comment] 2020-09-15 12:24
No.  You'd probably be better off asking the zabbix community how to integrate arbitrary data inputs.

**Comment by KavyaKanya** [comment] 2020-09-15 12:35
I've provided the parameter details also but still have an error

![image](https://user-images.githubusercontent.com/69708851/93210905-18aaad00-f77e-11ea-866d-7ff4740241a4.png)

**Comment by AspenForester** [comment] 2020-09-15 20:17
That seems pretty clear to me what the problem is.  I suggest looking up what a 401 error is (hint: search "http 401")

**Comment by lazywinadmin** [comment] 2020-09-16 05:29
@KavyaKanya Looks like you are using `Get-nbjobs` which is not part of the module, it is not an alias either imo.
As recommended by @AspenForester i would use:
* `Get-Help Get-NetBackupJob`
* `Get-Help Get-NetBackupJob` -examples
* `Get-Command Get-NetBackupJob -syntax`

The module is just a wrapper around the netbackup cmdlets, which was develop a while back

**Comment by KavyaKanya** [comment] 2020-09-16 12:24
got it sorted!

so d output of Get-NetBackupJob provides d started and ended time in epctime format I suppose as below in the screenshot

![image](https://user-images.githubusercontent.com/69708851/93336639-a7cec800-f845-11ea-9ab5-c32fbff89c88.png)


any suggestions how it can be converted to yyyy-MM-dd HH:mm:ss

**Comment by AspenForester** [comment] 2020-09-16 14:01
Of course, NetBackup always works in epoch time,   You should have no problems Googling how to convert epoch time to `[datetime]` with PowerShell.

**Comment by KavyaKanya** [comment] 2020-09-17 07:05
For each value of 'client' field how to get the Start Time End time Scheduletype (all d other columns) via d list of mentioned commands

I did try with d Get-Help too but no luck

![image](https://user-images.githubusercontent.com/69708851/93431841-53c5f100-f8e2-11ea-9c41-21dc65b944a6.png)

**Comment by KavyaKanya** [comment] 2020-09-18 03:08
> Of course, NetBackup always works in epoch time, You should have no problems Googling how to convert epoch time to `[datetime]` with PowerShell.

![image](https://user-images.githubusercontent.com/69708851/93550788-d786e880-f989-11ea-835b-0899763efda5.png)

I did try to convert epoc time to PS within d script when I individually run d commandsI get d ouput in PS console

=============
switch ($ITEM) {
  "TaskEndRunTime" {
[string] $jobid = $ID
#$name1 = $name.replace('&acirc;','Ã¢').replace('&agrave;','Ã ').replace('&ccedil;','Ã§').replace('&eacute;','Ã©').replace('&egrave;','Ã¨').replace('&ecirc;','Ãª')
$nametask = Get-NetBackupJob -JobId "$jobid"
$taskResult = $nametask.ended
$original = New-Object -Type DateTime -ArgumentList 1970, 1, 1, 7, 0, 0, 0, Utc
$time = $origin.AddSeconds($taskResult)
$taskResult1 = $time.ToString('yyyy-MM-dd HH:mm:ss')
Write-Output ($taskResult1)
}}
============

![image](https://user-images.githubusercontent.com/69708851/93550898-1ddc4780-f98a-11ea-909f-823bce32bbc2.png)

 but  get the below error in Zabbix for this particular item (when script is called and d data is expected to fed into Zabbix)

![image](https://user-images.githubusercontent.com/69708851/93550964-46fcd800-f98a-11ea-9c93-d192eb209f0d.png)

**Comment by lazywinadmin** [comment] 2020-09-18 04:15
@KavyaKanya for your datetime, you can use what @AspenForester recommended
```powershell
[datetimeoffset]::FromUnixTimeSeconds('1600254000').datetime
```

Regarding your loop question, manipulating these properties would look like:
```powershell
<your command> |select -property client, @{Label='started';Expression={[datetimeoffset]::FromUnixTimeSeconds($_.started).datetime}}
```

Closing this thread

**Closed by lazywinadmin** 2020-09-18 04:15 UTC

**Comment by KavyaKanya** [comment] 2020-09-18 04:57
> @KavyaKanya for your datetime, you can use what @AspenForester recommended
> 
> ```powershell
> [datetimeoffset]::FromUnixTimeSeconds('1600254000').datetime
> ```
> 
> Regarding your loop question, manipulating these properties would look like:
> 
> ```powershell
> <your command> |select -property client, @{Label='started';Expression={[datetimeoffset]::FromUnixTimeSeconds($_.started).datetime}}
> ```
> 
> Closing this thread

mmm! 

my point with the question was for each value of client I need to get rest columns like start time end time server schedule and all) any staright forward command within the NetbackupPS module wherein we send 'client' value

I was able to achieve via for each 'JobID' like below

==============

switch ($ITEM) {
  "DiscoverTasks" {
$apptasks = Get-NetBackupJob -Full -TimeStamp ((Get-Date).AddMinutes(-240))
#if (!$apptasks) {$apptasks = Get-BEJob -Jobtype Backup -Status Scheduled}
$apptasksok1 = $apptasks.jobid
$apptasksok = $apptasksok1.replace('Ã¢','&acirc;').replace('Ã ','&agrave;').replace('Ã§','&ccedil;').replace('Ã©','&eacute;').replace('Ã¨','&egrave;').replace('Ãª','&ecirc;')
#$jobtype = $apptasks.jobtype
$idx = 1
write-host "{"
write-host " `"data`":[`n"

foreach ($currentapptasks in $apptasksok)
{
    if ($idx -lt $apptasksok.count)
    {
     
        $line= "{ `"{#SYMANTECBACKUP}`" : `"" + $currentapptasks + "`" },"
        write-host $line
        
    }
    elseif ($idx -ge $apptasksok.count)
    {
    $line= "{ `"{#SYMANTECBACKUP}`" : `"" + $currentapptasks + "`" }"
    write-host $line
   
    }
    $idx++;
} 
write-host
write-host " ]"
write-host "}"}}

switch ($ITEM) {
  "TaskLastResult" {   
[string] $jobid = $ID
#$name1 = $name.replace('&acirc;','Ã¢').replace('&agrave;','Ã ').replace('&ccedil;','Ã§').replace('&eacute;','Ã©').replace('&egrave;','Ã¨').replace('&ecirc;','Ãª')
$nametask = Get-NetBackupJob -JobId "$jobid"
$nametask1 = $nametask.state
$nametask2 = "$nametask1".replace('queued and awaiting resources','1').replace('1','active').replace('2','requeued and awaiting resources').replace('3','done').replace('4','suspended').replace('5','incomplete')
Write-Output ($nametask2)#skip the string treplace 
}}

switch ($ITEM) {
  "TaskLastRunTime" {
[string] $jobid = $ID
#$name1 = $name.replace('&acirc;','Ã¢').replace('&agrave;','Ã ').replace('&ccedil;','Ã§').replace('&eacute;','Ã©').replace('&egrave;','Ã¨').replace('&ecirc;','Ãª')
$nametask = Get-NetBackupJob -JobId "$jobid"
$taskResult = $nametask.started
$original = New-Object -Type DateTime -ArgumentList 1970, 1, 1, 7, 0, 0, 0, Utc
$time = $original.AddSeconds($taskResult)
$taskResult1 = $time.ToString('yyyy-MM-dd HH:mm:ss')
Write-Output ($taskResult1)
}}

switch ($ITEM) {
  "TaskEndRunTime" {
[string] $jobid = $ID
#$name1 = $name.replace('&acirc;','Ã¢').replace('&agrave;','Ã ').replace('&ccedil;','Ã§').replace('&eacute;','Ã©').replace('&egrave;','Ã¨').replace('&ecirc;','Ãª')
$nametask = Get-NetBackupJob -JobId "$jobid"
$taskResult = $nametask.ended
$original = New-Object -Type DateTime -ArgumentList 1970, 1, 1, 7, 0, 0, 0, Utc
$time = $original.AddSeconds($taskResult)
$taskResult1 = $time.ToString('yyyy-MM-dd HH:mm:ss')
Write-Output ($taskResult1)
}}

=======================

so stuck with how d above can be achieve for sending in for each of 'client' as there is no PS command within d module any suggestions for this?
